<a href="https://colab.research.google.com/github/anncipher/Data_Science_Nigeria_Projects/blob/main/DSN_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# Creating a 1 dimensional array

x = np.array([1,2,3,4,5])
print(x)
print('The shape of X is', x.shape)

y = np.array([9,10])
print(y)
print('The shape of Y is', y.shape)


[1 2 3 4 5]
The shape of X is (5,)
[ 9 10]
The shape of Y is (2,)


In [ ]:
# Creating a 2D array

z = np.array([[1, 2], [3, 4]])
print(z)
print('The shape of Z is', z.shape)


[[1 2]
 [3 4]]
The shape of Z is (2, 2)


In [ ]:
# Creating a multidimensional array

w = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[26,27,28]]])
print(w)
print('The shape of W is', w.shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [26 27 28]]]
The shape of W is (3, 3, 3)


In [ ]:
# arange is used to create arrays with values in a specified range

A10 = np.arange(10)
A10
print(A10.shape)
print(A10)



(10,)
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# reshape is used to change a scalar matrix to vector

B10 = A10.reshape(-1,1)
print( A10, '\n', B10)
print('The shape of 1D array X =', B10.shape)

In [ ]:
A10 = B10.reshape(2,5)
print(A10)
print('The shape of 1D array X =', A10.shape)

In [ ]:
# zeros is used to create an array filled with zeros

np_Zeros = np.zeros((2,3))
np_Zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np_Zeros = np.zeros((2,3))
np_Zeros.astype(int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# ones is used to create an array filled with ones

np_Ones = np.ones((2,3))
np_Ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# full creates a n * n array filled with a specified given value

np_full = np.full((2,3), 4)
np_full

array([[4, 4, 4],
       [4, 4, 4]])

In [ ]:
# eye creates a n * n diagonal matrix

np_eye = np.eye(6,6)
np_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
# linspace returns equally spaced numbers over a specified interval

np_linspace = np.linspace(0, 10, num = 6)
np_linspace

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
# rand creates an array filled with random values between 0 and 1

np_rand = np.random.random_sample((2,3))
print(np_rand)
np.save('array_data.npy',np_rand)
np_rand1 = np.random.rand(2,3)
print(np_rand1)

X = np.random.randint(10, size=(5,3))
print(X)

[[0.92224408 0.19009249 0.53675609]
 [0.3197495  0.8836985  0.06308652]]
[[0.67092229 0.55048281 0.03096544]
 [0.02740433 0.6055962  0.07624304]]
[[7 2 7]
 [4 6 7]
 [0 6 4]
 [7 2 1]
 [7 1 2]]


In [ ]:
# Accessing elements of numpy array

# row 1, column 0 gives a scalar

print(z)
z[1,0]



[[1 2]
 [3 4]]


3

In [ ]:
# or

p = z[1][0]
p

3

In [ ]:
p = (z[0:1, 0])
p

array([1])

In [ ]:
import numpy as np
b = np.array([[1, 2], [3, 4], [5, 6 ]])
print(b)
print(b.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
# Numpy Attributes

# Shape: indicates the size of an array
# Size: returns the total number of elements in the NumPy array
# Dtype: returns the type of elements in the array, i.e., int64, character

In [ ]:
print('The Dtype of elements in array X =', x.dtype)
print('The shape of ND array W =', w.dtype)

The Dtype of elements in array X = int32
The shape of ND array W = int32


In [ ]:
print('The shape of arange A10 =', A10.size)
print('The shape of ND array W =', w.size)

The shape of arange A10 = 10
The shape of ND array W = 27


In [ ]:
# NumPy Array Math Operations

x = np.array ([[1,2,3], [4,5,6]])
y = np.array ([[2,2,2], [3,3,3]])
z = np.array ([1,2,3])

In [ ]:
# Transpose x matrix

x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Elementwise addition

print(x + y)
print(np.add(x,y))

[[3 4 5]
 [7 8 9]]
[[3 4 5]
 [7 8 9]]


In [ ]:
# Elementwise subtraction

print(x - y)
print(np.subtract(x,y))

[[-1  0  1]
 [ 1  2  3]]
[[-1  0  1]
 [ 1  2  3]]


In [ ]:
# Elementwise  multiplication

print(x * z)
print(np.multiply(x,z))

[[ 1  4  9]
 [ 4 10 18]]
[[ 1  4  9]
 [ 4 10 18]]


In [ ]:
# Elementwise division

print(x / y)
print(np.divide(x,y))

[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]
[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]


In [ ]:
# Inner product of vectors

print(np.dot(x,z), "\n")

[14 32] 

